config/routes.rb
Rails.application.routes.draw do
	root "users#new"

	get "signin", to: "sessions#new"
	post "signin", to: "sessions#create"
	delete "signout", to: "sessions#destroy"

  resources :flashcards do
    resources :reviews, only: [:create]
  end
  resources :scheduled_reviews, only: [:index, :show]
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create]
end

app/models/flashcard.rb
# == Schema Information
#
# Table name: flashcards
#
#  id                  :integer          not null, primary key
#  question            :string           not null
#  answer              :string           not null
#  difficulty          :decimal(, )      default(2.5)
#  user_id             :integer          not null
#  deck_id             :integer
#  scheduled_review_id :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  repetitions         :integer          default(0)
#  last_interval       :integer          default(0)
#
# Indexes
#
#  index_flashcards_on_deck_id              (deck_id)
#  index_flashcards_on_scheduled_review_id  (scheduled_review_id)
#  index_flashcards_on_user_id              (user_id)
#

class Flashcard < ActiveRecord::Base
  belongs_to :user
  belongs_to :deck
  belongs_to :scheduled_review

  has_many :reviews

  validates :question, :answer, presence: true

  def calculate_next_review
    if score < 3
      self.repetitions = 0
      interval = 0
    else
      new_difficulty = calculate_difficulty(difficulty_to_f, score)

      if score == 3
        interval = 0
      else
        case repetitions
        when 1
          interval = 1
        when 2
          interval = 6
        else
          interval = self.last_interval * new_difficulty
        end
      end
    end

    self.scheduled_review = ScheduledReview.create(scheduled_date: Date.today + interval.to_i, user: user)
    self.last_interval = interval.to_i
  end

  def schedule_next_review(interval, current_user)
    scheduled_date = Date.today + interval
    future_review = current_user.scheduled_reviews.find_by(scheduled_date: scheduled_date)

    if future_review
      future_review.flashcards << self
    else
      new_review = current_user.scheduled_reviews.create(scheduled_date: scheduled_date)
      new_review.flashcards << self
      ScheduledReviewEmailWorker.perform_at(new_review.scheduled_time, new_review.id)
    end
  end

  private

  def difficulty_to_f
    difficulty.to_f
  end

  def score
    reviews.last.score
  end

  def calculate_difficulty(difficulty, score)
    s = score
    d_old = difficulty

    result = d_old - 0.8 + (0.28*s) - (0.028*s*s)
    result < 1.3 ? 1.3 : result
  end
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  def index
    @flashcards = current_user.flashcards
  end

  def show
    @flashcard = current_user.flashcards.find(params[:id])
  end

  def new
    @flashcard = current_user.flashcards.new
  end

  def create
    @flashcard = current_user.flashcards.new(flashcard_params)

    if @flashcard.save
      create_or_add_to_scheduled_review(@flashcard)
      redirect_to user_path(current_user)
    else
      flash[:error] = "Please enter both a question AND an answer"
      redirect_to action: :new
    end
  end

  def update
    @flashcard = current_user.flashcards.find(params[:id])

    if @flashcard.update_attributes(flashcard_params)
      render :show
    else
      redirect_to action: :new
    end
  end

  def destroy
    @flashcard = current_user.flashcards.find(params[:id])
    @flashcard.destroy

    redirect_to :back
  end

  private

  def create_or_add_to_scheduled_review(flashcard)
    if current_user.scheduled_reviews.find_by(scheduled_date: Date.tomorrow)
      add_to_scheduled_review(flashcard)
    else
      create_scheduled_review
    end
  end

  def create_scheduled_review
    scheduled_review = current_user.scheduled_reviews.create(scheduled_date: Date.tomorrow)
    scheduled_review.flashcards << @flashcard
    ScheduledReviewEmailWorker.perform_at(scheduled_review.scheduled_time, scheduled_review.id)
  end

  def add_to_scheduled_review(flashcard)
    scheduled_review = current_user.scheduled_reviews.find_by(scheduled_date: Date.tomorrow)

    if scheduled_review.flashcards == []
      ScheduledReviewEmailWorker.perform_at(scheduled_review.scheduled_time, scheduled_review.id)
      scheduled_review.flashcards << flashcard
    else
      scheduled_review.flashcards << flashcard
    end
  end

  def flashcard_params
    params.require(:flashcard).permit(
      :question,
      :answer,
      :repetitions,
      :last_interval
    )
  end
end

app/views/flashcards/index.html.erb
<h2> My Mems (<%= @flashcards.count %>)</h2>
<%= render "shared/back" %>
<%= render "shared/error_message" %>
<br/><br/>

<div class="row">
<% @flashcards.each do |flashcard| %>
	<% div_id = flashcard.id %>
	<div class="col-md-6 col-xs-12 col-centered">
		<div class="flip-container flip-index" id="flip-<%= div_id %>">
			<div class="flipper">
				<div class="front well">
					<%= link_to flashcard_path(flashcard.id), :method => :delete do %>
  						<i class="glyphicon glyphicon-remove-sign delete-btn"></i>
					<% end %>
					<h2>Question</h2>
					<hr/>
					<%= flashcard.question %>
				</div>
				<div class="back well">
					<%= link_to flashcard_path(flashcard.id), :method => :delete do %>
  						<i class="glyphicon glyphicon-remove-sign delete-btn"></i>
					<% end %>
					<h2>Answer</h2>
					<hr/>
					<%= flashcard.answer %>
				</div>
			</div>
		</div>
		<br/>
		<button onclick="document.querySelector('#flip-<%= div_id %>').classList.toggle('hover');" class="btn btn-success" id="flip-btn">
			Flip over <i class="glyphicon glyphicon-refresh"></i>
		</button>
	</div>
<% end %>
</div>

app/views/flashcards/new.html.erb
<h2> New Mem </h2>
<%= render "shared/back" %>
<br/><br/>
<%= render "shared/error_message" %>
<br/>

<%= render "shared/flashcard_items" %>

app/views/flashcards/show.html.erb
<h2>Mems</h2>
<%= render "shared/back" %>
<br/><br/>

<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6 col-xs-12">
		<div class="flip-container">
			<div class="flipper">
				<div class="front well">
					<h2>Question</h2>
					<%= @flashcard.question %>
				</div>
				<div class="back well">
					<h2>Answer</h2>
					<%= @flashcard.answer %>
				</div>
			</div>
		</div>
		<br/>
		<button onclick="document.querySelector('.flip-container').classList.toggle('hover');" class="btn btn-success" id="flip-btn">
			Flip over <i class="glyphicon glyphicon-refresh"></i>
		</button>
	</div>
	<div class="col-md-3"></div>
</div>