config/routes.rb
Rails.application.routes.draw do
	root "users#new"

	get "signin", to: "sessions#new"
	post "signin", to: "sessions#create"
	delete "signout", to: "sessions#destroy"

  resources :flashcards do
    resources :reviews, only: [:create]
  end
  resources :scheduled_reviews, only: [:index, :show]
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :text
#  password_digest :text
#  first_name      :text
#  last_name       :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#

class User < ActiveRecord::Base
  has_secure_password

  has_many :flashcards
  has_many :scheduled_reviews

  accepts_nested_attributes_for :flashcards

  def signup_date
    created_at.to_date
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authenticate, only: [:new, :create]

  def new
    if signed_in?
      redirect_to user_path(current_user.id)
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params.merge(email: user_params[:email].downcase))

    if User.find_by(email: @user.email)
      flash[:error] = "An account with this email already exists"
      render :new
    elsif @user.save
      WelcomeEmail.new(@user).welcome
      sign_in @user
      if params[:user][:flashcard]
        scheduled_review = @user.scheduled_reviews.create(scheduled_date: Date.tomorrow)
        @user.flashcards.create(question: params[:user][:flashcard][:question], answer: params[:user][:flashcard][:answer], scheduled_review: scheduled_review)
      end

      render :show
    else
      flash[:error] = "Please enter a valid email address and password"
      render :new
    end
  end

  def show
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/views/users/new.html.erb
<div class="row">
	<%= render "shared/error_message" %>
	<div class="col-md-3"></div>
	<div class="col-md-6 col-xs-12">
		<%= form_for :user, url: users_path do |user| %>
		<%= user.fields_for :flashcard do |flashcard| %>

		<div class="well">
			<h2>Write your question here...</h2>
			<%= flashcard.text_field :question, class: "form-control" %>
			<br/>

			<h2>...and write your answer here!</h2>
			(*hint: pull on the bottom right corner of the text box for more room)<br/>
			<%= flashcard.text_area :answer, class: "form-control" %>
			<% end %>
			<br/>
		</div>

		<button type="button" class="btn btn-success btn-flashcard" data-toggle="modal" data-target="#newAccountModal">
			Create Mem <i class="glyphicon glyphicon-plus"></i>
		</button>
	</div>
	<div class="col-md-3"></div>
</div>

<!-- New Account Modal -->
<div class="modal fade" id="newAccountModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Account Creation</h4>
      </div>

	<!-- Create Account -->
	<div class="col-md-12 well">
		<h2>Start Studying Now!</h2>
			<div class="field form-group">
				<%= user.label :email %>
				<%= user.text_field :email, class: 'form-control' %>
			</div>

			<div class="field form-group">
				<%= user.label :password %>
				<%= user.password_field :password, class: 'form-control' %>
			</div>

			<%= user.submit 'Create Account', class: 'btn btn-danger' %>
		<% end %>
	</div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<h3>If you already have an account, <a href="#" data-toggle="modal" data-target="#signinModal">sign in here</a></h3>
	</div>
	<div class="col-md-3"></div>
</div> <!-- Row -->

<!-- Sign in  Modal -->
<div class="modal fade" id="signinModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Welcome back!</h4>
      </div>
  	<!-- Sign In -->
	<div class="col-md-12 well">
	    <h2>Sign in</h2>
	    <%= form_for :session, url: signin_path do |f| %>
	      <div class="field form-group">
	        <%= f.label :email %>
	        <%= f.text_field :email, class: "form-control" %>
	      </div>

	      <div class="field form-group">
	        <%= f.label :password %>
	        <%= f.password_field :password, class: "form-control" %>
	      </div>

	      <%= f.submit "Login", class: "btn btn-danger" %>
	    <% end %>
	</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render "shared/dashboard_items" %>
<%= render "shared/flashcard_items" %>