config/routes.rb
Rails.application.routes.draw do
	root "users#new"

	get "signin", to: "sessions#new"
	post "signin", to: "sessions#create"
	delete "signout", to: "sessions#destroy"

  resources :flashcards do
    resources :reviews, only: [:create]
  end
  resources :scheduled_reviews, only: [:index, :show]
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create]
end

app/views/shared/_back.html.erb
<a href="/">&#8592; Back to dashboard</a>

app/views/shared/_banner.html.erb
<div class="row" id="banner">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<a href="/"><%= image_tag "facebook-cover2.jpg" %></a>
	</div>
	<div class="col-md-3 status">
	</div>
</div>

app/views/shared/_dashboard_items.html.erb
<h2>Dashboard</h2>

<div class="row dashboard">
	<div class="col-md-4 well">
		<span>Account Information</span>
		<hr/>
		Logged in as <%= current_user.email %> <br/>
		<% if user_date == Date.today %>
			Thanks for creating an account! Let's get studying!
		<% else %>
			Member since <%= user_date.to_formatted_s(:long) %>
		<% end %>
	</div>

	<div class="col-md-4 well">
		<span>Manage Mems</span>
		<hr/>
		<%= link_to "Create a new Mem", new_flashcard_path %> <br/>
		<%= link_to "My Mems", flashcards_path %> (<%= current_user.flashcards.count %>)
	</div>

	<div class="col-md-4 well">
		<span>Scheduled Reviews</span>
		<hr/>
		<% to_study = flashcards_count %>
		You have <%= to_study %> <%= link_to " Mems", scheduled_reviews_path %> to study today <br/>
		<% if flashcards_count > 0 %>
			<%= link_to "Study now", scheduled_review_path(current_scheduled_review) %>
		<% else %>
			<% if current_user.flashcards.count > 0  %>
				No Mems to study today! Review your cards <%= link_to "here", flashcards_path %>
			<% else %>
				<%= link_to "Create Mems", new_flashcard_path %> and start studying now!
			<% end %>
		<% end %>
	</div>
</div>

app/views/shared/_error_message.html.erb
<% if flash[:notice] %>
	<div class="alert alert-warning">
	    <a href="#" class="close" data-dismiss="alert">&times;</a>
	    <strong>Oops!</strong> <%= flash[:notice] %>
	</div>
<% end %>

<% if flash[:error] %>
	<div class="alert alert-warning">
	    <a href="#" class="close" data-dismiss="alert">&times;</a>
	    <strong>Oops!</strong> <%= flash[:error] %>
	</div>
<% end %>

app/views/shared/_finished.html.erb
<div class="finished-message">
	<% SuccessMessage.new.message.each do |message| %> <br/><br/>
		<%= message %>
	<% end %>
</div>

app/views/shared/_flashcard_items.html.erb
<div class="row">
	<div class="col-md-6 col-xs-12 col-centered">
		<%= form_for :flashcard, url: flashcards_path do |f| %>
		<div class="flipper well">
			<h2>Question</h2>
			<hr/>
			<%= f.text_field :question, class: "form-control" %>
			<br/>

			<h2>Answer</h2>
			<hr/>
			<%= f.text_area :answer, class: "form-control" %>
			<br/>
		</div>
			
		<%= button_tag 'Create Mem', class: 'btn btn-success btn-flashcard' do %>
			Create Mem <i class="glyphicon glyphicon-plus"></i>
		<% end %>
		<% end %>
	</div>
</div> <!-- Row -->

app/views/shared/_infographic.html.erb
<div class="row" id="infographic">
	<%= image_tag 'memknow-infogr.png' %>
</div>

app/views/shared/_login_items.html.erb
<% if !current_user = GuestUser %>
  	<%= link_to signout_path, class: 'btn btn-sucess' do %>
  		<i class="glyphicon glyphicon-minus"></i> Logout
  	<% end %>
    <%= link_to("Logout", signout_path, method: :delete) %>
<% else %>
	<li>
    <%= link_to users_path do %>
    	Login<i class="glyphicon glyphicon-plus"></i>
    </li>
    <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><%= image_tag "horizontal-logo.jpg" %></a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <div class="status">
                <%= link_to scheduled_reviews_path do %>
                <i class="glyphicon glyphicon-folder-close"></i>
                <div class="number-overlay">
                    <%= flashcards_count %>
                </div>
                <% end %>

                <%= link_to signout_path, method: :delete do %>
                    <i class="glyphicon glyphicon-off"></i>
                <% end %>
            </div>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="/"><img src="app/assets/images/Profile-icon-yellow.jpg"></a>
		  	<%= render "shared/registration_items" %>
		  	<%= render "shared/login_items" %>
		</div>
	</div>
</nav>

app/views/shared/_registration_items.html.erb
<% if !current_user=GuestUser %>
    <%= link_to("Edit Registration", edit_user_registration_path, method: :delete) %>
<% else %>
	<li>
	<%= link_to new_user_path do %>
		Register<i class="glyphicon glyphicon-plus"></i>
	<% end %>
	</li>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="col-sm-3 col-md-3">
    <div class="panel-group" id="accordion">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-th">
                    </span>Flashcards</a>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse">
              <!--
                <div class="panel-body">
                    <table class="table">
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-pencil text-primary"></span><a href="#"></a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-flash text-success"></span><a href="http://www.jquery2dotnet.com">News</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-file text-info"></span><a href="http://www.jquery2dotnet.com">Newsletters</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-comment text-success"></span><a href="http://www.jquery2dotnet.com">Comments</a>
                                <span class="badge">42</span>
                            </td>
                        </tr>
                    </table>
                </div>
                -->
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><span class="glyphicon glyphicon-calendar">
                    </span>Calendar</a>
                </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse">
                <div class="panel-body">
                    <table class="table">
                        <tr>
                            <td>
                                <a href="http://www.jquery2dotnet.com">Orders</a> <span class="label label-success">$ 320</span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <a href="http://www.jquery2dotnet.com">Invoices</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <a href="http://www.jquery2dotnet.com">Shipments</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <a href="http://www.jquery2dotnet.com">Tex</a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><span class="glyphicon glyphicon-user">
                    </span>Account</a>
                </h4>
            </div>
            <div id="collapseThree" class="panel-collapse collapse">
                <div class="panel-body">
                    <table class="table">
                        <tr>
                            <td>
                                <a href="http://www.jquery2dotnet.com">Change Password</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <a href="http://www.jquery2dotnet.com">Notifications</a> <span class="label label-info">5</span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <a href="http://www.jquery2dotnet.com">Import/Export</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-trash text-danger"></span><a href="http://www.jquery2dotnet.com" class="text-danger">
                                    Delete Account</a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour"><span class="glyphicon glyphicon-stats">
                    </span>Report Card</a>
                </h4>
            </div>
            <div id="collapseFour" class="panel-collapse collapse">
                <div class="panel-body">
                    <table class="table">
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-usd"></span><a href="http://www.jquery2dotnet.com">Sales</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-user"></span><a href="http://www.jquery2dotnet.com">Customers</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-tasks"></span><a href="http://www.jquery2dotnet.com">Products</a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="glyphicon glyphicon-shopping-cart"></span><a href="http://www.jquery2dotnet.com">Shopping Cart</a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>