config/routes.rb
Rails.application.routes.draw do
	root "users#new"

	get "signin", to: "sessions#new"
	post "signin", to: "sessions#create"
	delete "signout", to: "sessions#destroy"

  resources :flashcards do
    resources :reviews, only: [:create]
  end
  resources :scheduled_reviews, only: [:index, :show]
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create]
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = current_flashcard.reviews.new(review_date: Date.today, score: submitted_score)

    if @review.save
      interval = @review.flashcard.calculate_next_review
      @review.flashcard.schedule_next_review(interval, current_user)

      redirect_to :back
    else
      render :new
    end
  end

  private

  def submitted_score
    case params[:commit]
    when ":("
      1
    when "Ehhh"
      2
    when "Not bad"
      3
    when "Aced"
      4
    end
  end

  def current_flashcard
    current_user.flashcards.find(params[:flashcard_id])
  end
end

app/views/reviews/_new.html.erb
<div class="review-buttons">
<%= form_for :review, url: flashcard_reviews_path(flashcard) do |f| %>
	<div class="col-md-3 col-xs-3">
		<%= f.submit ":(", class: "btn btn-danger" %>
	</div>
	<div class="col-md-3 col-xs-3">
		<%= f.submit "Ehhh", class: "btn btn-warning" %>
	</div>
	<div class="col-md-3 col-xs-3">
		<%= f.submit "Not bad", class: "btn btn-info" %>
	</div>
	<div class="col-md-3 col-xs-3">
		<%= f.submit "Aced", class: "btn btn-success" %>
	</div>
<% end %>
</div>